filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - '/var/lib/docker/containers/logs/app_log*.log'
    exclude_lines: ['^DEBUG']
    multiline.pattern: ^(DEBUG|INFO|ERROR|TRACE|FATAL|WARN).*
    multiline.negate: true
    multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]